name: nba-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  - pip
  # Data processing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.0
  - xgboost>=1.4.0
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  # Development
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  # Code quality
  - pytest>=6.2.0
  - black
  - flake8
  # Additional requirements
  - pip:
    - nba_api>=1.1.9
    - python-dotenv>=0.19.0
